export const SEASONS = [
	{
		season: 1,
		episodes: [
			'Pilot',
			'Lawnmower Dog',
			'Anatomy Park',
			'M. Night Shaym-Aliens!',
			'Meeseeks and Destroy',
			'Rick Potion #9',
			'Raising Gazorpazorp',
			'Rixty Minutes',
			'Something Ricked This Way Comes',
			'Close Rick-counters of the Rick Kind',
			'Ricksy Business',
		],
	},
	{
		season: 2,
		episodes: [
			'A Rickle in Time',
			'Mortynight Run',
			'Auto Erotic Assimilation',
			'Total Rickall',
			'Get Schwifty',
			'The Ricks Must Be Crazy',
			'Big Trouble in Little Sanchez',
			'Interdimensional Cable 2: Tempting Fate',
			"Look Who's Purging Now",
			'The Wedding Squanchers',
		],
	},
	{
		season: 3,
		episodes: [
			'The Rickshank Rickdemption',
			'Rickmancing the Stone',
			'Pickle Rick',
			'Vindicators 3: The Return of Worldender',
			'The Whirly Dirly Conspiracy',
			'Rest and Ricklaxation',
			'The Ricklantis Mixup',
			"Morty's Mind Blowers",
			"The ABC's of Beth",
			'The Rickchurian Mortydate',
		],
	},
	{
		season: 4,
		episodes: [
			'Edge of Tomorty: Rick Die Rickpeat',
			'The Old Man and the Seat',
			"One Crew over the Crewcoo's Morty",
			"Claw and Hoarder: Special Ricktim's Morty",
			'Rattlestar Ricklactica',
			'Never Ricking Morty',
			'Promortyus',
			'The Vat of Acid Episode',
			'Childrick of Mort',
			'Star Mort Rickturn of the Jerri',
		],
	},
	{
		season: 5,
		episodes: [
			'Mort Dinner Rick Andre',
			'Mortyplicity',
			'A Rickconvenient Mort',
			'Rickdependence Spray',
			'Amortycan Grickfitti',
			"Rick & Morty's Thanksploitation Spectacular",
			'Gotron Jerrysis Rickvangelion',
			'Rickternal Friendshine of the Spotless Mort',
			'Forgetting Sarick Mortshall',
			'Rickmurai Jack',
		],
	},
	{
		season: 6,
		episodes: [
			'Solaricks',
			'Rick: A Mort Well Lived',
			'Bethic Twinstinct',
			'Night Family',
			'Final DeSmithation',
			'JuRicksic Mort',
			'Full Meta Jackrick',
			'Analyze Piss',
			'A Rick in King Mortur’s Mort',
			'Ricktional Mortpoon’s Rickmas Mortcation',
		],
	},
	{
		season: 7,
		episodes: [
			'How Poopy Got His Poop Back',
			'The Jerrick Trap',
			'Air Force Wong',
			"That's Amorte",
			'Unmortricken',
			'Rickfending Your Mort',
			'Wet Kuat Amortican Summer',
			'Rise of the Numbericons: The Movie',
			'Mort: Ragnarick',
			'Fear No Mort',
		],
	},
	{
		season: 8,
		episodes: [
			'Summer of All Fears',
			'Valkyrick',
			'The Rick, The Mort & The Ugly',
			'The Last Temptation of Jerry',
			'Cryo Mort a Rickver',
			'The Curicksous Case of Bethjamin Button',
			'Ricker than Fiction',
			'Nomortland',
			'Morty Daddy',
			'Hot Rick',
		],
	},
]
